export const projects = [
  {
    title: "Mecânica promocional",
    description:
      " Desenvolvimento de Micro Front-End para Geração de Cupons, utilizado pela Controladoria da Livelo",
    src: "livelo-new-logo.svg",
    link: "https://www./",
    color: "#808080",
    icon: [
      "icon-0",
      "icon-react",
      "icon-scrum",
      "icon-jest",
      "icon-javascript",
      "icon-figma",
      "icon-git",
      "icon-nodejs",
      "icon-jira",
      "icon-styled-components",
      "icon-gitlab",
    ],
    empresa: "Livelo",
  },
  {
    title: "Precificação de Passagens Aéreas",
    description:
      "Desenvolvimento de Portal Administrativo para Precificação de Passagens Aéreas.",
    src: "livelo-new-logo.svg",
    link: "https://www./",
    color: "#808080",
    icon: [
      "icon-react",
      "icon-scrum",
      "icon-jest",
      "icon-javascript",
      "icon-figma",
      "icon-git",
      "icon-nodejs",
      "icon-jira",
      "icon-styled-components",
      "icon-gitlab",
    ],
    empresa: "Livelo",
  },
  {
    title: "Checkout Porto",
    description:
      "Participação desde o início no desenvolvimento do sistema de carrinho e checkout, garantindo a implementação das regras de negócio definidas para a equipe.",
    src: "Logos_Porto.svg",
    link: "https://www./",
    color: "#808080",
    icon: [
      "icon-react",
      "icon-scrum",
      "icon-jest",
      "icon-javascript",
      "icon-git",
      "icon-nodejs",
      "icon-jira",
      "icon-figma",
      "icon-aem",
      "icon-bitbucket",
      "icon-styled-components",
    ],
    empresa: "Porto",
  },
  {
    title: "Site institucional Edge.uol",
    description:
      "Colaboração no desenvolvimento do site institucional Edge.UOL desde o zero, incluindo a criação de novas seções e a implementação de um formulário de contato.",
    src: "edge.svg",
    link: "https://www./",
    color: "#808080",
    icon: [
      "icon-react",
      "icon-scrum",
      "icon-javascript",
      "icon-figma",
      "icon-git",
      "icon-nodejs",
      "icon-jira",
      "icon-aem",
      "icon-bitbucket",
      "icon-styled-components",
    ],

    empresa: "Edge",
  },
  {
    title: "Listagem de produtos",
    description:
      "Aprimoramento da seção de listagem de produtos, visando usabilidade, a estética e a eficiência, proporcionando uma experiência mais agradável e intuitiva aos usuários durante a navegação.",
    src: "converse.svg",
    link: "https://www./",
    color: "#808080",
    icon: [
      "icon-scrum",
      "icon-php",
      "icon-less",
      "icon-javascript",
      "icon-figma",
      "icon-git",
      "icon-jira",
      "icon-adobe-comm",
      "icon-bitbucket",
    ],

    empresa: "Converse",
  },
];
