export const projects = [
  {
    title: "Mecânica promocional",
    description:
      "Desenvolvimento de portal administrativo para a criação de cupons destinados aos clientes do clube de pontos.",
    src: "livelo-new-logo.svg",
    link: "https://www./",
    color: "#808080",
    icon: [
      "icon-0",
      "icon-react",
      "icon-scrum",
      "icon-jest",
      "icon-javascript",
      "icon-figma",
      "icon-git",
      "icon-nodejs",
      "icon-jira",
      "icon-styled-components",
      "icon-gitlab",
    ],
    empresa: "Livelo",
  },
  {
    title: "Checkout",
    description:
      "Desenvolvimento de sistema de carrinho de compras, juntamente com uma experiência de checkout eficiente," +
      " visando proporcionar aos usuários uma jornada de compra intuitiva.",
    src: "Logos_Porto.svg",
    link: "https://www./",
    color: "#808080",
    icon: [
      "icon-react",
      "icon-scrum",
      "icon-jest",
      "icon-javascript",
      "icon-git",
      "icon-nodejs",
      "icon-jira",
      "icon-figma",
      "icon-aem",
      "icon-bitbucket",
      "icon-styled-components",
    ],
    empresa: "Porto",
  },
  {
    title: "Site institucional",
    description:
      "Criação de um novo site institucional Edge, destacando-se pela inovação e modernidade em design.",
    src: "edge.svg",
    link: "https://www./",
    color: "#808080",
    icon: [
      "icon-react",
      "icon-scrum",
      "icon-javascript",
      "icon-figma",
      "icon-git",
      "icon-nodejs",
      "icon-jira",
      "icon-aem",
      "icon-bitbucket",
      "icon-styled-components",
    ],

    empresa: "Edge",
  },
  {
    title: "Listagem de produtos",
    description:
      "Aprimoramento da seção de listagem de produtos, visando usabilidade, a estética e a eficiência, proporcionando uma experiência mais agradável e intuitiva aos usuários durante a navegação.",
    src: "converse.svg",
    link: "https://www./",
    color: "#808080",
    icon: [
      "icon-scrum",
      "icon-php",
      "icon-less",
      "icon-javascript",
      "icon-figma",
      "icon-git",
      "icon-jira",
      "icon-adobe-comm",
      "icon-bitbucket",
    ],

    empresa: "Converse",
  },
];
